version: '2'
services:
    trievego-app:
        image: trievego
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://trievego-mariadb:3306/trievego
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trievego-mariadb:
        extends:
            file: mariadb.yml
            service: trievego-mariadb
